name: Build and deploy Node.js app to Azure Web App - Parkhill-tech

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Backend install
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # Frontend install and build
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Package backend and built frontend
      - name: Prepare deployment artifact
        run: |
          mkdir deploy
          cp -r backend deploy/
          cp -r frontend/dist deploy/

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FDA54A533F02449DA49F7C7F4E9FB1EB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F8BE1A8742DE4AF59B7611DC2D1008DF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1816699F3EBE4C9597F22A5069B425B8 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Parkhill-tech'
          slot-name: 'Production'
          package: deploy/